### ISSUE TITLE
Просьбы сделать вид SteamID2

### ISSUE THREAD

**Issue by ghostss2016** [komashchenko/MiniVIP#3]
Очень большая просьба SteamID2 или же понимание системой. как в кс2банс.
Заранее благодарю. 
все випки в ксго к примеру забиты так, и портировать их в новый формат руками это просто ад.

**Comment by komashchenko** [comment]
Могу добавить поддержку SteamID64 (765XXXXXXXXXXXXXX), SteamID2 и SteamID3 не буду, планирую перевод плагина на MySQL вместо конфига, там будет только SteamID32

**Comment by ghostss2016** [comment]
ну давай 64, в целом у нас везде стимид2 в движках , ну раз так, тогда временно сделаем конвертацию сами. и будем переходить в 32 или 64. Спасибо, ждем с нетерпением. Скажи как можно поблагадорить ? Плагин то что нужно. А главное вовремя.
