### ISSUE TITLE
SDK version

### ISSUE THREAD

**Issue by marqdevx** [komashchenko/MiniVIP#8]
Hey! What version of the SDK are you using?

I'm trying to integrate the clan tag on one addon, but I get compilation issues.
Thanks

**Comment by strteamservidores** [comment]
im trying to find this sdk version too but i can't. Have a way to change this SDK to CS2Fixes SDK ?

**Comment by komashchenko** [comment]
You can use the latest version of the SDK https://github.com/alliedmodders/hl2sdk/tree/cs2

**Comment by strteamservidores** [comment]
it would be necessary to change the code right?

**Comment by komashchenko** [comment]
No, it builds successfully with current version
https://github.com/komashchenko/MiniVIP/actions/runs/6684004886

**Comment by strteamservidores** [comment]
what about these [files](https://github.com/komashchenko/MiniVIP/tree/master/sdk)? you created?

**Comment by marqdevx** [comment]
If you are using the raw sdk, you can use a git-submodule, so it will point to the exact commit that you want.

**Comment by komashchenko** [comment]
> If you are using the raw sdk, you can use a git-submodule, so it will point to the exact commit that you want.

SDK should always be up to date
